gpg: C5C84658CCFD7E8E71DEE933AF3AE54FC3A35C9F
url: "https://asciimoth.github.io/testdebrpm"

deb:
  origin: "asciimoth"
  label: "asciimoth"
  name: "asciimoth-test-deb-rpm"
  description: "My personal APT and RPM repo"

rpm:
  name: "asciimoth-test-deb-rpm"

